In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
np.diff(a)

array([1, 1, 1, 1])

In [6]:
expected_diff_price = np.ones((3,6))
diff = list(zip(*expected_diff_price))

In [11]:
expected_diff_price

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
for i in expected_diff_price:
    print(i)

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]


In [7]:
diff

[(1.0, 1.0, 1.0),
 (1.0, 1.0, 1.0),
 (1.0, 1.0, 1.0),
 (1.0, 1.0, 1.0),
 (1.0, 1.0, 1.0),
 (1.0, 1.0, 1.0)]

In [13]:
np.arange(5)[::-1]

array([4, 3, 2, 1, 0])

In [14]:
.5* np.tile(np.identity(2),[4,1,1])

array([[[0.5, 0. ],
        [0. , 0.5]],

       [[0.5, 0. ],
        [0. , 0.5]],

       [[0.5, 0. ],
        [0. , 0.5]],

       [[0.5, 0. ],
        [0. , 0.5]]])